# Fake News Detection using Machine Learning

This project builds a text classification model to distinguish between real and fake news articles using TF-IDF and Logistic Regression.

## Dataset

- Source: Fake.csv and True.csv  
- Total samples: ~45,000  
- Balanced distribution between real (1) and fake (0)

In [39]:
import pandas as pd

fake = pd.read_csv('Fake.csv')
true = pd.read_csv('True.csv')

fake['label'] = 0
true['label'] = 1

df = pd.concat([fake, true])
df = df.sample(frac = 1).reset_index(drop = True)

df = df[['text', 'label']]

print('Dataset shape:', df.shape)
print('\nClass distribution:\n', df['label'].value_counts())
df.head()

Dataset shape: (44898, 2)

Class distribution:
 label
0    23481
1    21417
Name: count, dtype: int64

                                                text  label
0  Who knew the Middle East had a prestigious sch...      0
1  BEIJING (Reuters) - China s foreign ministry o...      1
2                                                         0
3  (Reuters) - Democrat Hillary Clinton and Repub...      1
4  A man shouting  Allahu Akbar  has stabbed two ...      0

## Text Preprocessing

- Lowercasing  
- Removing URLs, punctuation, numbers  
- Removing noise patterns (e.g., source tags like Reuters)

In [40]:
import re
import string

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>+', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub(r'\n', '', text)
    text = re.sub(r'\w*\d\w*', '', text)
    text = re.sub(r'\(reuters\)', '', text.lower())
    return text

df['clean_text'] = df['text'].apply(clean_text)

df.head()

,text,label,clean_text
0,Who knew the Middle East had a prestigious sch...,0,who knew the middle east had a prestigious sch...
1,BEIJING (Reuters) - China s foreign ministry o...,1,beijing reuters china s foreign ministry on w...
2,,0,
3,(Reuters) - Democrat Hillary Clinton and Repub...,1,reuters democrat hillary clinton and republic...
4,A man shouting Allahu Akbar has stabbed two ...,0,a man shouting allahu akbar has stabbed two ...

In [3]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\FAIZAN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\FAIZAN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\FAIZAN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\FAIZAN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\FAIZAN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.6.0)

## Train-Test Split

- 80% training data  
- 20% testing data

In [4]:
from sklearn.model_selection import train_test_split

X = df['clean_text']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

print('Train size:', X_train.shape)
print('Test size:', X_test.shape)

Train size: (35918,)
Test size: (8980,)

In [15]:
print("Train label distribution:")
print(y_train.value_counts())

print("\nTest label distribution:")
print(y_test.value_counts())

Train label distribution:
label
0    18783
1    17135
Name: count, dtype: int64

Test label distribution:
label
0    4698
1    4282
Name: count, dtype: int64

## Feature Extraction

- TF-IDF vectorization  
- Maximum features: 5000

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("TF-IDF shape (train):", X_train_tfidf.shape)
print("TF-IDF shape (test):", X_test_tfidf.shape)

TF-IDF shape (train): (35918, 5000)
TF-IDF shape (test): (8980, 5000)

## Model Training

- Algorithm: Logistic Regression  
- Class balancing enabled

In [48]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight='balanced', max_iter=1000, solver = 'liblinear')
model.fit(X_train_tfidf, y_train)
print("Training successful")

Training successful

In [49]:
y_pred = model.predict(X_test_tfidf)

In [50]:
model.predict_proba(X_test_tfidf[:5])

array([[0.8702804 , 0.1297196 ],
       [0.86151669, 0.13848331],
       [0.02693624, 0.97306376],
       [0.00255245, 0.99744755],
       [0.01502499, 0.98497501]])

## Model Evaluation

- Accuracy score  
- Classification report  
- Confusion matrix

In [51]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n", classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.987305122494432

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      4698
           1       0.98      0.99      0.99      4282

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980


Confusion Matrix:
 [[4631   67]
 [  47 4235]]

## Sample Predictions

Testing the model on custom news statements

In [52]:
samples = [
    "India has signed a new trade agreement with the European Union to strengthen economic cooperation and increase exports, government officials said on Tuesday.",
    
    "Scientists from NASA have reported new findings about water presence on Mars.",
    
    "You won’t believe what this politician secretly did behind closed doors to gain power!",
    
    "This miracle cure is guaranteed to completely change your life overnight with no side effects!"
]

for s in samples:
    cleaned = clean_text(s)
    vec = tfidf.transform([cleaned])
    pred = model.predict(vec)[0]
    
    print("Text:", s)
    
    if pred == 1:
        print("Prediction: Real")
    else:
        print("Prediction: Fake")
    
    print()

Text: India has signed a new trade agreement with the European Union to strengthen economic cooperation and increase exports, government officials said on Tuesday.
Prediction: Real

Text: Scientists from NASA have reported new findings about water presence on Mars.
Prediction: Fake

Text: You won’t believe what this politician secretly did behind closed doors to gain power!
Prediction: Fake

Text: This miracle cure is guaranteed to completely change your life overnight with no side effects!
Prediction: Fake

## Explainability

To understand how the model makes decisions, we analyze the learned coefficients from Logistic Regression.

- Words with higher positive weights contribute to predicting real news
- Words with lower (negative) weights contribute to predicting fake news

This helps interpret which textual patterns the model relies on.

In [53]:
feature_names = tfidf.get_feature_names_out()
coefficients = model.coef_[0]

top_real = sorted(zip(coefficients, feature_names), reverse=True)[:10]
top_fake = sorted(zip(coefficients, feature_names))[:10]

print("Top words indicating REAL news:")
for coef, word in top_real:
    print(word, round(coef, 3))

print("\nTop words indicating FAKE news:")
for coef, word in top_fake:
    print(word, round(coef, 3))

Top words indicating REAL news:
reuters 25.779
said 19.234
on 8.617
washington 5.92
us 4.834
in 4.709
wednesday 4.624
tuesday 4.381
thursday 4.238
republican 4.193

Top words indicating FAKE news:
via -8.258
this -5.872
just -4.86
that -4.778
is -4.725
image -4.58
gop -4.454
mr -4.37
hillary -4.083
wire -3.822

## Limitations

- The model relies heavily on writing style rather than factual correctness  
- Performs well on structured news articles but struggles with short or context-limited inputs  
- Dataset bias (e.g., source-specific patterns like Reuters) affects generalization  
- The model does not verify real-world truth, only textual patterns